### ISSUE TITLE
install.sh pkgbuilds are not correct anymore

### ISSUE THREAD

**Issue by atxr** [goatfiles/dotfiles#33]
With the recent PR that renamed the pkgbuilds, the install.sh script is not correct anymore.

**Comment by amtoine** [comment]
definitely right and definitely caused me some trouble when reinstalling my system :sweat_smile:

**Comment by amtoine** [comment]
i see two ways to fix that:
- force the revision with
```diff
diff --git a/install.sh b/install.sh
index 64afc24..e3fd9d6 100644
--- a/install.sh
+++ b/install.sh
@@ -21,6 +21,7 @@ git clone https://github.com/goatfiles/pkgbuilds /tmp/pkgbuilds
 # Build pkgbuilds
 (
     cd /tmp/pkgbuilds
+    git checkout 996ade4
     ./install.sh x86_64/paru
     ./install.sh x86_64/amtoine-scripts-git/
     ./install.sh x86_64/amtoine-sounds-git/
```
we could even add a tag to this revision, `996ade4` :+1: 
- fix the names of the packages in `install.sh`

**Comment by atxr** [comment]
> definitely right and definitely caused me some trouble when reinstalling my system sweat_smile

So do I yesterday :laughing: 
Which solution suits the best for you?

**Comment by amtoine** [comment]
> Which solution suits the best for you?
>
i think the latter is the best
we need to transition to the new package names :+1:

**Comment by atxr** [comment]
> i was thinking about that and maybe we should fix the version of the `pkgbuilds` in the script:
> 
>     * move to the latest revision, i.e. [goatfiles/pkgbuilds@70357a6](https://github.com/goatfiles/pkgbuilds/commit/70357a661581e53e6a31b5a412a21c337926643f),  and fix the script
> 
>     * checkout to [goatfiles/pkgbuilds@70357a6](https://github.com/goatfiles/pkgbuilds/commit/70357a661581e53e6a31b5a412a21c337926643f) in the script to make sure new revision of the `pkgbuilds` won't break the script

Mmm I don't know, it's weird to update by hand the checkout in the install script each time we commit on pkgbuilds :thinking:

**Comment by amtoine** [comment]
good point and i think i have an idea about this :smirk: 
i'll probably open a new discussion about that very soon :wink:

**Comment by amtoine** [comment]
there it is @atxr :yum: 
https://github.com/goatfiles/dotfiles/discussions/37
